name: Build for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # можно запускать вручную

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      id: install-qt
      with:
        version: '6.8.*'          # ← если у тебя 6.7, 6.5 или 5.15 — поменяй здесь!
        host: windows
        target: desktop
        arch: win64_mingw
        install-deps: true

    - name: Configure CMake
      shell: bash
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release \
                 -G "MinGW Makefiles"

    - name: Build
      shell: bash
      run: |
        cd build
        cmake --build . --config Release --parallel

    - name: Deploy Qt deps
      shell: bash
      run: |
        cd build
        windeployqt --release open_work.exe \
                    --dir deploy

    - name: Package
      run: Compress-Archive -Path build/deploy/* -DestinationPath open_work-windows.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: open_work-windows.zip
